trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Ensure you're using a valid image name, e.g., ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'  # Running tests
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'  # Use JDK from the environment
    jdkVersionOption: '11'  # Ensure JDK 11 is used
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'  # Adjust JVM heap size
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Ensure JDK 11 is used
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'  # Running package
